src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Un compte est déjà associé par cet email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $Adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $Ville = null;

    #[ORM\Column(length: 255)]
    private ?string $Pays = null;

    #[ORM\Column(length: 255)]
    private ?string $Code_postale = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): static
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): static
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(string $Ville): static
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->Pays;
    }

    public function setPays(string $Pays): static
    {
        $this->Pays = $Pays;

        return $this;
    }

    public function getCodePostale(): ?string
    {
        return $this->Code_postale;
    }

    public function setCodePostale(string $Code_postale): static
    {
        $this->Code_postale = $Code_postale;

        return $this;
    }
}

templates/profil/edit.html.twig
{# templates/profil/edit.html.twig #}
{% extends 'base.html.twig' %}

{% block title %}Modifier le Profil{% endblock %}

{% block body %}
<h1 class="text-center">Modifier le Profil</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            {{ form_start(form) }}
                <div class="form-group text-white">
                    
                    {{ form_label(form.Prenom,'Prénom')}}
                    {{ form_widget(form.Prenom, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors(form.Prenom) }}
                </div>
                <div class="form-group text-white">
                    {{ form_label(form.Nom) }}
                    {{ form_widget(form.Nom, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors(form.Nom) }}
                </div>
                <div class="form-group text-white">
                    {{ form_label(form.email) }}
                    {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors(form.email) }}
                </div>
                <div class="form-group text-white">
                    {{ form_label(form.adresse) }}
                    {{ form_widget(form.adresse, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors(form.adresse) }}
                </div>
                <div class="form-group text-white">
                    {{ form_label(form.ville) }}
                    {{ form_widget(form.ville, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors(form.ville) }}
                </div>
                <div class="form-group text-white">
                    {{ form_label(form.codepostale,'code postale') }}
                    {{ form_widget(form.codepostale, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors(form.codepostale) }}
                </div>
                <div class="form-group text-white">
                    {{ form_label(form.pays) }}
                    {{ form_widget(form.pays, {'attr': {'class': 'form-control'}}) }}
                    {{ form_errors(form.pays) }}
                </div>
                <div class="d-flex justify-content-between align-items-center">
                <button type="submit" class="btn btn-custom mt-3">Enregistrer</button>
            {{ form_end(form) }}
              <a href="{{ path('app_profil') }}" class="btn btn-secondary mt-3">Annuler</a>
               <a href="{{ path('app_profil_delete') }}" class="btn btn-danger mt-3">Supprimer</a>
               </div>
        </div>
    </div>
</div>
<style>
       .btn-custom:hover {
        background-color: white; /* Couleur de fond au survol */
        color: blue; /* Couleur du texte au survol */
    }
</style> 
{% endblock %}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil{% endblock %}

{% block body %}

<!-- Ajoutez d'autres informations que vous souhaitez afficher -->

<h1 class="text-orange fs-name text-center">Bonjour {{ app.user.Prenom }}</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10"> <!-- Utilisation de col-lg-10 pour occuper plus de 3/4 de l'écran sur les écrans larges -->
      <div class="card mb-3 bg-dark">
        <img src="{{ asset('images/profil.webp') }}" class="card-img-top" alt="...">
        <div class="card-body d-flex flex-column justify-content-center align-items-center">
          <h5 class="card-text pro-name text-center">{{ app.user.Nom }} {{ app.user.Prenom }}</h5>
          <p class="card-title text-white text-center fs-4">{{ app.user.email }}</p>
          <h5 class="card-title text-white text-center fs-2">{{ app.user.adresse }}</h5>
          <h5 class="card-title text-white text-center fs-2">{{ app.user.ville }} {{ app.user.codepostale }}</h5>
          <h5 class="card-title text-white text-center fs-2">{{ app.user.pays }}</h5>
          
          <a href="{{ path('app_orders_history') }}" class="btn btn-custom mt-3">Mes commandes</a>
          <a href="{{ path('app_profil_edit') }}" class="btn btn-warning mt-3">Modifier</a>
        </div>
      </div>
    </div>
  </div>
</div> 

<style>
    .card {
        border: 1px solid white; /* Définir la bordure de la carte en blanc */
    }
    .btn-custom:hover {
        background-color: white; /* Couleur de fond au survol */
        color: blue; /* Couleur du texte au survol */
    }
    .pro-name {
        color: white;
        -webkit-text-stroke-width: 2px;
        -webkit-text-stroke-color: rgb(0, 140, 255);
        font-size: 6rem;
    }
    .fs-name {
        font-size: 5rem;
    }
</style> 

{% endblock %}